server:
  port: ${TWTODO_SERVER_PORT}
spring:
  datasource:
    url: jdbc:mysql://${TWTODO_DB_HOST}:${TWTODO_DB_PORT}/${TWTODO_DB_NAME}?serverTimezone=UTC
    username: ${TWTODO_DB_USER}
    password: ${TWTODO_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        "[format_sql]": false
